### ISSUE TITLE
Build error on MacOS: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'

### ISSUE THREAD

**Issue by hencomb** [const-void/DOOM-fire-zig#30]
zig version: 0.15.1
MacOS: 15.6.1

Compilation fails on fresh clone.

% git clone https://github.com/const-void/DOOM-fire-zig/
% cd DOOM-fire-zig/
% zig build run
build.zig:20:10: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'
        .root_source_file = b.path("src/main.zig"),
         ^~~~~~~~~~~~~~~~
/usr/local/Cellar/zig/0.15.1/lib/zig/std/Build.zig:771:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~
referenced by:
    runBuild__anon_20530: /usr/local/Cellar/zig/0.15.1/lib/zig/std/Build.zig:2214:33
    main: /usr/local/Cellar/zig/0.15.1/lib/zig/compiler/build_runner.zig:366:29
    4 reference(s) hidden; use '-freference-trace=6' to see all references

with -freference-trace=6:

referenced by:
    runBuild__anon_20530: /usr/local/Cellar/zig/0.15.1/lib/zig/std/Build.zig:2214:33
    main: /usr/local/Cellar/zig/0.15.1/lib/zig/compiler/build_runner.zig:366:29
    callMain [inlined]: /usr/local/Cellar/zig/0.15.1/lib/zig/std/start.zig:627:37
    callMainWithArgs [inlined]: /usr/local/Cellar/zig/0.15.1/lib/zig/std/start.zig:587:20
    main: /usr/local/Cellar/zig/0.15.1/lib/zig/std/start.zig:602:28
    comptime: /usr/local/Cellar/zig/0.15.1/lib/zig/std/start.zig:62:30

**Comment by dustinbowers** [comment]
I think you'll need to downgrade to Zig 0.13 or earlier to compile the current repo as is

**Comment by Darep** [comment]
Note: compiles ok on zig v0.14.1 -- zig 0.15 removed some deprecated stuff which breaks the build, see here: https://ziglang.org/download/0.15.1/release-notes.html#Removed-Deprecated-Implicit-Root-Module

**Comment by ashugg** [comment]
Confirming that I see the same issue in macOS 14.7.8 with Zig 0.15.1

Darep's PR resolves it for me

**Comment by danodonovan** [comment]
I wasn't having a lot of luck with the other PR  -- #33 works for me now

**Comment by adex345** [comment]
Same issue with archlinux

**Comment by hencomb** [comment]
resolved in Zig 0.15.2

**Comment by x11x** [comment]
I'm getting this issue with Zig 0.16.0 on Linux (Fedora)
